# This file was generated by GoReleaser. DO NOT EDIT.
cask "ney" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "a8f478144b87f415b1c607317ba0a9008c5a8bc2cfddfeec16af489fc857b3b1"
      url "https://github.com/naay99999/neything/releases/download/v#{version}/ney_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "12aed48bbf2db070181495b0c9bd1adbd13109b605acd47922b78632a11a83a8"
      url "https://github.com/naay99999/neything/releases/download/v#{version}/ney_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ae9827c4b39f24144d568ad2ffcbb719631bb7e1c0584eb423891bf3af34ebef"
      url "https://github.com/naay99999/neything/releases/download/v#{version}/ney_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a459290ad8e822b854a4831b26145d6f9ae0aa848801251a2de4ce8e5cc96f24"
      url "https://github.com/naay99999/neything/releases/download/v#{version}/ney_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ney"
  desc "Local-first MCP server + CLI that gives AI clients search and read access to your local documents"
  homepage "https://github.com/naay99999/neything"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ney"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ney"]
    end
  end

  # No zap stanza required

end
